name: API Cypress Tests
on:
  push:
    branches:
      - main
      - feature/create-pipeline
  pull_request:
    branches:
      - main
      - feature/create-pipeline
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                record: true
                group: QAzando - API Pipeline
              env:
                CYPRESS_RECORD_KEY: a5dec7d9-9696-4664-ad92-47ebd1bb3c91